### ISSUE TITLE
Remove the compass compiler dependency

### ISSUE THREAD

**Issue by RVenkatesh** [RVenkatesh/Ember-Slider#13]
Replace compass compiler plugin with node sass

**Comment by Kilowhisky** [comment]
Just tried to install this into a fresh project and my build exploded as compass is not a command.

```
Build Error (CompassCompiler)

Command failed: compass compile --output-style=compressed --sass-dir=C:/.../node_modules/@love-open-source/ember-slider/addon/styles --css-dir="C:\Users\....\AppData\Local\Temp\broccoli-76764hGOVbDo0nNlf\out-271-compass_compiler"
'compass' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by RVenkatesh** [comment]
@Kilowhisky Since ember compass compiler uses [http://compass-style.org/install/](Compass) as dependency to compile scss files used in the addon, you need to install it using the following link http://compass-style.org/install/

As mentioned in this ticket, once we figure out a way to remove compass without disturbing the existing functionality, we roll this out. Let me know in case you need further help.

**Comment by RVenkatesh** [comment]
v1.2.0 removes the dependency of using compass and instead uses ember-cli-sass.

**Comment by Kilowhisky** [comment]
Thanks! You Rock!
