### ISSUE TITLE
Issue new tag release after bumping node-sass from 4.13.1 to 7.0.0

### ISSUE THREAD

**Issue by J4RF** [RVenkatesh/Ember-Slider#34]
Can you issue a new tag release? I currently have to use the Github repo URL in my package.json files because @love-open-source/ember-slider from the npm registry installs 1.2.7, which does not contain the node-sass version bump. I am unable to install the package without the new node-sass version.

**Comment by RVenkatesh** [comment]
@J4RF 

A new version is now published with latest changes. 

Sorry for any inconvenience caused.

**Comment by J4RF** [comment]
No problem, thanks for the quick response! Helps me out trying to upgrade some projects to newer Ember versions.
